--
-- PostgreSQL database dump
--

-- Dumped from database version 9.5.4
-- Dumped by pg_dump version 9.5.4

-- Started on 2016-08-31 23:37:05 EEST
--
-- SET DATABASE SQL SYNTAX PGS TRUE;
-- CREATE USER SA PASSWORD '';
-- ALTER USER SA SET LOCAL TRUE;
--
-- CREATE SCHEMA "public";
-- --WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'C' LC_CTYPE = 'C';
--
-- SET SCHEMA "public";

CREATE SEQUENCE attached_file_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
;

CREATE TABLE attached_file (
    id integer GENERATED BY DEFAULT AS SEQUENCE attached_file_id_seq PRIMARY KEY,
    created_by_id integer NOT NULL,
    date_create timestamp without time zone NOT NULL,
    filename character varying(100),
    filesize integer,
    deleted boolean,
    url_file character varying(255),
    file BINARY,
    contact_id integer,
    company_id integer,
    deal_id integer
);



CREATE SEQUENCE company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
;

CREATE TABLE company (
    id integer GENERATED BY DEFAULT AS SEQUENCE company_id_seq PRIMARY KEY,
    name character varying(200) NOT NULL,
    phone character varying(45) NOT NULL,
    email character varying(320) NOT NULL,
    address character varying(200) NOT NULL,
    responsible_user_id integer NOT NULL,
    web character varying(255),
    deleted boolean,
    created_by_id integer NOT NULL,
    date_create timestamp without time zone
);

CREATE SEQUENCE contact_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
;

CREATE TABLE contact (
    id integer GENERATED BY DEFAULT AS SEQUENCE contact_id_seq PRIMARY KEY,
    name character varying(300) NOT NULL,
    responsible_user_id integer NOT NULL,
    "position" character varying(100),
    type_of_phone integer NOT NULL,
    company_id integer,
    phone character varying(45),
    skype character varying(32),
    email character varying(320),
    deleted boolean,
    date_create timestamp without time zone,
    created_by_id integer NOT NULL
);

CREATE SEQUENCE contact_company_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
;

CREATE TABLE contact_company_tag (
    id integer GENERATED BY DEFAULT AS SEQUENCE contact_company_tag_id_seq PRIMARY KEY,
    contact_id integer FOREIGN KEY REFERENCES contact,
    tag_id integer NOT NULL,
    company_id integer FOREIGN KEY REFERENCES company,
    deleted boolean
);


CREATE TABLE currency (
    id integer NOT NULL,
    name character varying(45) NOT NULL,
    active boolean,
    deleted boolean
);


CREATE TABLE stage_deals (
    id integer NOT NULL PRIMARY KEY,
    name character varying(100) NOT NULL,
    deleted boolean
);

CREATE SEQUENCE deal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
;

CREATE TABLE deal (
    id integer GENERATED BY DEFAULT AS SEQUENCE deal_id_seq PRIMARY KEY,
    name character varying(200) NOT NULL,
    stage_id integer NOT NULL FOREIGN KEY REFERENCES stage_deals,
    responsible_user_id integer,
    amount numeric(20,2),
    company_id integer NOT NULL FOREIGN KEY REFERENCES company,
    deleted boolean,
    date_create timestamp without time zone,
    created_by_id integer NOT NULL,
    primary_contact_id integer FOREIGN KEY REFERENCES contact
);

CREATE TABLE deal_contact (
    deal_id integer NOT NULL,
    contact_id integer NOT NULL
);


CREATE TABLE deal_tag (
    deal_id integer NOT NULL,
    tag_id integer NOT NULL
);

CREATE TABLE language (
    id integer NOT NULL PRIMARY KEY,
    name character varying(45) NOT NULL,
    code character(2) NOT NULL,
    deleted boolean
);


CREATE SEQUENCE note_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
;

CREATE TABLE note (
    id integer GENERATED BY DEFAULT AS SEQUENCE note_id_seq PRIMARY KEY,
    note character varying(500),
    created_by_id integer NOT NULL,
    date_create timestamp without time zone NOT NULL,
    deleted boolean,
    deal_id integer,
    company_id integer,
    contact_id integer
);


CREATE SEQUENCE rights_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
;

CREATE TABLE rights (
    id integer GENERATED BY DEFAULT AS SEQUENCE rights_id_seq PRIMARY KEY,
    user_id integer NOT NULL,
    subject_type integer NOT NULL,
    subject_type_create boolean,
    subject_type_read boolean,
    subject_type_delete boolean,
    subject_type_change boolean,
    subject_type_export boolean,
    deleted boolean
);


CREATE SEQUENCE tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
;

CREATE TABLE tag (
    id integer GENERATED BY DEFAULT AS SEQUENCE tag_id_seq PRIMARY KEY,
    name character varying(1000) NOT NULL,
    deleted boolean
);

CREATE SEQUENCE task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
;

CREATE TABLE task (
    id integer GENERATED BY DEFAULT AS SEQUENCE task_id_seq PRIMARY KEY,
    period integer NOT NULL,
    responsible_user_id integer NOT NULL,
    task_type_id integer NOT NULL,
    created_by_id integer NOT NULL,
    name character varying(500),
    status_id integer NOT NULL,
    deleted boolean,
    date_create timestamp without time zone NOT NULL,
    company_id integer,
    contact_id integer,
    deal_id integer,
    date_task date,
    time_task character varying(20)
);


CREATE TABLE task_status (
    id integer NOT NULL PRIMARY KEY,
    name character varying(100) NOT NULL,
    deleted boolean
);

CREATE TABLE task_type (
    id integer NOT NULL PRIMARY KEY,
    name character varying(100) NOT NULL,
    deleted boolean
);

CREATE SEQUENCE user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
;

CREATE TABLE "user" (
    id integer GENERATED BY DEFAULT AS SEQUENCE user_id_seq PRIMARY KEY,
    name character varying(100) NOT NULL,
    email character varying(320) NOT NULL,
    password character varying(32) NOT NULL,
    is_admin boolean,
    phone character varying(45),
    mobile_phone character varying(45),
    note character varying(300),
    deleted boolean,
    image BINARY,
    url character varying(255),
    language_id integer NOT NULL
);

CREATE SEQUENCE visit_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
;

CREATE TABLE visit_history (
    id integer GENERATED BY DEFAULT AS SEQUENCE visit_history_id_seq PRIMARY KEY,
    user_id integer NOT NULL,
    date_create timestamp without time zone NOT NULL,
    ip_address character varying(45),
    browser character varying(255),
    deleted boolean
);

--
-- ALTER TABLE attached_file ALTER COLUMN id SET DEFAULT nextval('attached_file_id_seq'::regclass);
--
--
--
-- ALTER TABLE company ALTER COLUMN id SET DEFAULT nextval('company_id_seq'::regclass);
--
--
--
-- ALTER TABLE contact ALTER COLUMN id SET DEFAULT nextval('contact_id_seq'::regclass);
--
--
--
-- ALTER TABLE contact_company_tag ALTER COLUMN id SET DEFAULT nextval('contact_company_tag_id_seq'::regclass);
--
--
--
-- ALTER TABLE deal ALTER COLUMN id SET DEFAULT nextval('deal_id_seq'::regclass);
--
--
--
-- ALTER TABLE note ALTER COLUMN id SET DEFAULT nextval('note_id_seq'::regclass);
--
--
--
-- ALTER TABLE rights ALTER COLUMN id SET DEFAULT nextval('rights_id_seq'::regclass);
--
--
--
-- ALTER TABLE tag ALTER COLUMN id SET DEFAULT nextval('tag_id_seq'::regclass);
--
--
--
-- ALTER TABLE task ALTER COLUMN id SET DEFAULT nextval('task_id_seq'::regclass);
--
--
--
-- ALTER TABLE "user" ALTER COLUMN id SET DEFAULT nextval('user_id_seq'::regclass);
--
--
--
-- ALTER TABLE visit_history ALTER COLUMN id SET DEFAULT nextval('visit_history_id_seq'::regclass);
--

ALTER TABLE deal_contact
    ADD CONSTRAINT deal_contact_pkey PRIMARY KEY (deal_id, contact_id);

ALTER TABLE deal_tag
    ADD CONSTRAINT deal_tag_pkey PRIMARY KEY (deal_id, tag_id);


ALTER TABLE "user"
    ADD CONSTRAINT user_email_key UNIQUE (email);


--
-- TOC entry 2360 (class 2606 OID 16726)
-- Name: user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

--
-- TOC entry 2413 (class 2606 OID 16912)
-- Name: attached_file_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE attached_file
    ADD CONSTRAINT attached_file_company_id_fkey FOREIGN KEY (company_id) REFERENCES company(id);


--
-- TOC entry 2412 (class 2606 OID 16907)
-- Name: attached_file_contact_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE attached_file
    ADD CONSTRAINT attached_file_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contact(id);


--
-- TOC entry 2414 (class 2606 OID 16917)
-- Name: attached_file_deal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE attached_file
    ADD CONSTRAINT attached_file_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES deal(id);


--
-- TOC entry 2393 (class 2606 OID 16750)
-- Name: company_created_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE company
    ADD CONSTRAINT company_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES "user"(id);


--
-- TOC entry 2392 (class 2606 OID 16745)
-- Name: company_responsible_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE company
    ADD CONSTRAINT company_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES "user"(id);


--
-- TOC entry 2396 (class 2606 OID 16776)
-- Name: contact_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE contact
    ADD CONSTRAINT contact_company_id_fkey FOREIGN KEY (company_id) REFERENCES company(id);

--
-- ALTER TABLE contact_company_tag
--     ADD CONSTRAINT contact_company_tag_company_id_fkey FOREIGN KEY (company_id) REFERENCES company(id);
--
-- ALTER TABLE contact_company_tag
--     ADD CONSTRAINT contact_company_tag_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contact(id);

ALTER TABLE contact_company_tag
    ADD CONSTRAINT contact_company_tag_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES tag(id);


--
-- TOC entry 2395 (class 2606 OID 16771)
-- Name: contact_created_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE contact
    ADD CONSTRAINT contact_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES "user"(id);


--
-- TOC entry 2394 (class 2606 OID 16766)
-- Name: contact_responsible_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE contact
    ADD CONSTRAINT contact_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES "user"(id);


--
-- TOC entry 2399 (class 2606 OID 16799)
-- Name: deal_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--
--
-- ALTER TABLE deal
--     ADD CONSTRAINT deal_company_id_fkey FOREIGN KEY (company_id) REFERENCES company(id);


--
-- TOC entry 2417 (class 2606 OID 16945)
-- Name: deal_contact_contact_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE deal_contact
    ADD CONSTRAINT deal_contact_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contact(id);


--
-- TOC entry 2416 (class 2606 OID 16940)
-- Name: deal_contact_deal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE deal_contact
    ADD CONSTRAINT deal_contact_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES deal(id);


--
-- TOC entry 2400 (class 2606 OID 16804)
-- Name: deal_created_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE deal
    ADD CONSTRAINT deal_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES "user"(id);


ALTER TABLE deal
    ADD CONSTRAINT deal_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES "user"(id);



ALTER TABLE deal_tag
    ADD CONSTRAINT deal_tag_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES deal(id);


ALTER TABLE deal_tag
    ADD CONSTRAINT deal_tag_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES tag(id);

ALTER TABLE note
    ADD CONSTRAINT note_company_id_fkey FOREIGN KEY (company_id) REFERENCES company(id);


ALTER TABLE note
    ADD CONSTRAINT note_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contact(id);


ALTER TABLE note
    ADD CONSTRAINT note_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES "user"(id);


--
-- TOC entry 2409 (class 2606 OID 16881)
-- Name: note_deal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE note
    ADD CONSTRAINT note_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES deal(id);


--
-- TOC entry 2415 (class 2606 OID 16930)
-- Name: rights_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE rights
    ADD CONSTRAINT rights_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user"(id);


--
-- TOC entry 2405 (class 2606 OID 16850)
-- Name: task_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE task
    ADD CONSTRAINT task_company_id_fkey FOREIGN KEY (company_id) REFERENCES company(id);


--
-- TOC entry 2406 (class 2606 OID 16855)
-- Name: task_contact_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE task
    ADD CONSTRAINT task_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contact(id);


--
-- TOC entry 2402 (class 2606 OID 16835)
-- Name: task_created_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE task
    ADD CONSTRAINT task_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES "user"(id);


--
-- TOC entry 2407 (class 2606 OID 16860)
-- Name: task_deal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE task
    ADD CONSTRAINT task_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES deal(id);


--
-- TOC entry 2401 (class 2606 OID 16830)
-- Name: task_responsible_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE task
    ADD CONSTRAINT task_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES "user"(id);


--
-- TOC entry 2404 (class 2606 OID 16845)
-- Name: task_status_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE task
    ADD CONSTRAINT task_status_id_fkey FOREIGN KEY (status_id) REFERENCES task_status(id);


--
-- TOC entry 2403 (class 2606 OID 16840)
-- Name: task_task_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE task
    ADD CONSTRAINT task_task_type_id_fkey FOREIGN KEY (task_type_id) REFERENCES task_type(id);


--
-- TOC entry 2391 (class 2606 OID 16729)
-- Name: user_language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE "user"
    ADD CONSTRAINT user_language_id_fkey FOREIGN KEY (language_id) REFERENCES language(id);


--
-- TOC entry 2418 (class 2606 OID 16958)
-- Name: visit_history_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE visit_history
    ADD CONSTRAINT visit_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user"(id);


--
-- TOC entry 2544 (class 0 OID 0)
-- Dependencies: 6
-- Name: public; Type: ACL; Schema: -; Owner: postgres
--
--
-- REVOKE ALL ON SCHEMA FROM PUBLIC;
-- GRANT ALL ON SCHEMA TO PUBLIC;

-- Completed on 2016-08-31 23:37:05 EEST

--
-- PostgreSQL database dump complete
--